Repository susverma/Hacktoberfest_2022, pull requests merged in 2022-09, with the labels that each got.

#2 deep learning program
  casava_efficientnetB3_71_without_augument.ipynb
Labels: hacktoberfest-accepted

#3 Add files via upload
  count_sequences_sum.cpp
Labels: hacktoberfest-accepted, hacktoberfest2022

#5 sum upto n in c++
  sum upto N-1.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#4 changes by ankul
  calc.py
Labels: hacktoberfest, hacktoberfest-accepted

#6 third commit
  calc.py
Labels: hacktoberfest-accepted, hacktoberfest2022

#7 new feature by ankul
  calc.py
Labels: hacktoberfest2022

#8 new feature added by Ankul
  calc.py
Labels: hacktoberfest, hacktoberfest-accepted

#12 Create calculator.py
  calculator.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#13 Create dimond.py
  dimond.py
Labels: hacktoberfest, hacktoberfest-accepted

#15 Keep hustling
  Constructor.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#16 Add files via upload
  merge_sort.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#17 replace_case.java
  replace_case.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022
